# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_auto_20190414_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='choice_text',
        ),
    ]
